[build]
  command = "npm run build"
  publish = "dist"
  NODE_VERSION = "8.15.1"

[context.deploy-preview]
  command = "npm run build-preview"

[context.production.environment]
  HUGO_VERSION = "0.29"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.29"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.29"

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"
