baseurl = "/"
languageCode = "en-us"
title = "Sierra Jones"

[params]
  description = "The homepage of Daniel A.R. Evans, or Dare."
  
[[menu.main]]
  name = "Shop"
  url = "http://dracowolfie.tictail.com/"

[[menu.main]]
  name = "Commissions"
  url = "/commission"
